/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dpyle' at '1/31/16 1:26 PM' with Gradle 2.6
 *
 * @author dpyle, @date 1/31/16 1:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
